### ISSUE TITLE
EWC的实现问题

### ISSUE THREAD

**Issue by deadpool66** [which47/LLMCL#1]
我注意到在EWC的代码实现中，对于每个任务计算的是当前任务的fisher。但是根据我对原论文的理解和对其他EWC实现的参考，此处应该计算旧任务的fisher，再应用于当前任务来计算loss。
期待作者的解答。

**Comment by which47** [comment]
您好，感谢您提出的问题！我们在每一步结束更新fisher矩阵而不是在每个任务结束后更新，是希望损失函数变化的平缓而不至于导致训练不稳定以及产生的其他问题，我们在编写代码时参考了这个仓库[https://github.com/2proveit/TRACE/blob/469d265827c4b1f680d633e32b72b1faa75b1dbd/model/Regular/EWC.py#L123](https://github.com/2proveit/TRACE/blob/469d265827c4b1f680d633e32b72b1faa75b1dbd/model/Regular/EWC.py#L123) 希望对您有帮助，感谢您的关注
